apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 2
  selector:
    matchLabels:
      # manage pods with the label app: si3mshady/strayaway
      si3mshady: node
      
  template:
    metadata:
      labels:        
        si3mshady: node
    spec:
      containers:
      - name: node
        image:  si3mshady/tiktok-clone-be:1.1 
        ports:
        - containerPort: 9000
          hostPort: 9000

--- 
apiVersion: v1
kind: Service
metadata: 
  name: node
spec: 
  ports: 
    - port: 9000
      targetPort: 9000    
      # nodePort: 30300
  selector: 
    si3mshady: node
  type: LoadBalancer
