apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      # manage pods with the label app: si3mshady/strayaway
      si3mshady: node
      si3mshady: reactfrontend
    
  template:
    metadata:
      labels:
        si3mshady: node
        si3mshady: reactfrontend
    spec:
      containers:
      - name: reactfrontend
        image:  si3mshady/tiktok-clone-fe:1.3  #1.2 uses intance ip addr instead of service name 
        
        ports:
        - containerPort: 80
          hostPort: 888

--- 
apiVersion: v1
kind: Service
metadata: 
  name: reactfrontend

spec: 
  ports: 
    - port: 888
      targetPort: 80     
    
  selector: 
    si3mshady: reactfrontend
  type: LoadBalancer