apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      # manage pods with the label app: si3mshady/db
      si3mshady: db
    
  template:
    metadata:
      labels:        
        si3mshady: db
    spec:
      volumes: 
      - name: tiktok-volume-mount
        persistentVolumeClaim:
          claimName: tiktok-pvc

      containers:
      - name: db
        image:  mongo:latest
        ports:
        - containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: tiktok-volume-mount    
          mountPath: /data/db
--- 
apiVersion: v1
kind: Service
metadata: 
  name: db
spec: 
  ports: 
    - port: 27017
      targetPort: 27017         
  selector: 
    si3mshady: db
  type: ClusterIP