kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: tiktok-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4 
reclaimPolicy: Retain
mountOptions:
  - debug
#make storage class default  
#kubectl patch storageclass tiktok-gp2 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}' --namespace=ns-eks-course
---
#PVC 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiktok-pvc
  labels:
    si3mshady: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 88Gi